### PR TITLE
CI tests

### PR DESCRIPTION
**Pull request by ewels**
Continuous integration tests - validate markdown style using [markdownlint-cli](https://github.com/igorshubovych/markdownlint-cli)

Rules: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

### CODE REVIEW

**Comment by talavis** [comment]
I guess I can't accept it since it failed ;)

**Comment by ewels** [comment]
This should now make each pull-request and commit have an automated test which checks the markdown. It will fail for annoying reasons like having trailing spaces at the end of lines, or too many line breaks in a row. However, it will force all contributors to write markdown in the same style, and should catch certain problems before they become an issue.

**Comment by ewels** [comment]
That's weird - why can't it open the config file? Looks fine to me.. 🤔

**Comment by ewels** [comment]
This is an exact copy of the code we use in nf-core [eg. here](https://github.com/nf-core/rnaseq/blob/3b6df9bd104927298fcdf69e97cca7ff1f80527c/.github/workflows/linting.yml#L5-L18). So I'm not sure why it's failing.. 😕

**Comment by ewels** [comment]
`yml` not `yaml` 🤦

**Pull request merged**
