### PR TITLE
Adding data tables feature v.1

### PR DESCRIPTION
**Pull request by akochari**
- For now, only in English; Swedish version coming soon
- The database of entries is at this point manually created (markdown files with json syntax inside for each entry). The goal is to generate these files automatically from an actual database. That will be v.2, and also coming soon.

### CODE REVIEW

**Comment by talavis** [comment]
Is it possible to rename all the data files to `.json`? Currently markdownlint is going crazy at all the files.

**Comment by akochari** [comment]
> Is it possible to rename all the data files to `.json`? Currently markdownlint is going crazy at all the files.

Unfortunately Hugo would not like that. It has to be an .md file.

**Comment by ewels** [comment]
I think that Hugo is expecting markdown files because of where you are putting them. The `content/` folder is specifically for web pages / posts, hence the expectation of markdown.

I would argue that these files are not really web pages and so you can put them somewhere in `static/`. Then you should be able to have whatever file format you want.

**Comment by akochari** [comment]
> I think that Hugo is expecting markdown files because of where you are putting them. The `content/` folder is specifically for web pages / posts, hence the expectation of markdown.
> 
> I would argue that these files are not really web pages and so you can put them somewhere in `static/`. Then you should be able to have whatever file format you want.

I am afraid it was not possible to make a solution like that work (at least I didn't manage to). Hugo has the option to have data files, in the /data/ folder. And one is meant to use .json files there indeed. I can do that, but then Hugo does not allow pagination to happen. This is the reason why I had to put those in the /content/ folder. If we give up on pagination, then one idea is to have a single .json file with all of the data that is needed. However, this file will also be difficult to manage.

Moreover, while these are in the /content/ folder, html pages for these files are not generated. They are only needed at the stage of rendering the static version. They do not go anywhere else.

**Comment by ewels** [comment]
Ok cool - sounds like you have already spent plenty of  time looking at this, I'll shut up 😉

**Pull request merged**
