### PR TITLE
Readme docs

### PR DESCRIPTION
**Pull request by ewels**
Wrote some documentation in the repository readme, with contribution instructions.

### CODE REVIEW

**Comment by ewels** [comment]
Can preview on my fork here: https://github.com/ewels/covid-portal/blob/readme-docs/README.md

**Comment by pekrau** [comment]
Look exactly like what I needed! I haven't tested in detail, let's merge it and correct later if any issues

**Comment by pekrau** [comment]
Question: In point 2a, how does one keep one's fork up to date with the original repo? That is, what is the corresponding operation for `git pull upstream develop` in 2b?

**Comment by ewels** [comment]
`git pull upstream develop` _is_ to keep one's fork up to date with the original repo..

Maybe that bit of text needs work to make it clearer! 😅

**Comment by pekrau** [comment]
OK, but I was asking about **2a**, how one does it if one uses only GitHub, and not a local repo.

**Comment by pekrau** [comment]
Looks good. Please merge as far as I am concerned.

**Pull request merged**
