### PR TITLE
New VR fund on pandemics

### PR DESCRIPTION
**Pull request by senthil10**

### CODE REVIEW

**Review by LianeHughes — CHANGES_REQUESTED** [review]
It looks good, but we have a few more fields that we can fill in with this call (I think that you may have copied from one where not all fields were included). If you look, for example, at 'Societal Security Beyond COVID-19' in the funding file, then there are also 'applicant', 'funding_period' and 'decision_date' fields that we can use. Perhaps we could consider having somewhere where we keep 'full templates' that we can copy and paste from. I've been thinking about it for a while. What do you think?

**Comment by senthil10** [comment]
Yes, I copy pasted from the recent one, will make the changes.
And having a full template somewhere do sound good :+1:

**Comment by senthil10** [comment]
@LianeHughes and done!

**Review by LianeHughes — APPROVED** [review]
It looks good now. Thank you. I'll merge to develop for now. We'll make whatever else we have live tomorrow.

**Pull request merged**
