### PR TITLE
Updated links to graphics and dataset for NPC statistics. Swedish page.

### PR DESCRIPTION
**Pull request by pekrau**

### CODE REVIEW

**Comment by talavis** [comment]
Looks a bit off on mobile (no scrolling on the graphs). Is that supposed to be included?

**Comment by ewels** [comment]
Looks like this is missing the extra CSS required for the mobile graphs. Half of this is already merged into the feature branch, the required CSS is there..

**Comment by ewels** [comment]
See https://github.com/ScilifelabDataCentre/covid-portal/pull/124

**Comment by talavis** [comment]
I cherry-picked the "css commit" and removed the non-css part. Seems to work as intended now.

Do we want any changes to the Swedish graphs (Swedish instead of English inside them)?

**Comment by ewels** [comment]
Thanks @talavis!

**Comment by pekrau** [comment]
Sorry, but the graphcs are the one and the same for English and Swedish. So only English right now. Will think about this for later.

**Pull request merged**
